sylius_resource:
    resources:
        app.family:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Family


fos_rest:
    disable_csrf_role: ROLE_API
    view:
        formats:
            xml:  true
            json: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
